### PR TITLE
fix typo: 'KTK_CUBE_UUID_SEPERATOR' -> 'KTK_CUBE_UUID_SEPARATOR'

### PR DESCRIPTION
**Pull request by lr4d**
# Description:

Fix two typos, add a comment about ktk/ktk.cube inconsistency

- [ ] Closes #xxxx
- [ ] Changelog entry

### CODE REVIEW

**Comment by lr4d** [comment]
[Test failure](https://github.com/JDASoftwareGroup/kartothek/pull/422/checks?check_run_id=1971406917) looks unrelated

**Comment by fjetter** [comment]
In principle, I'm ok with the change. however, I'm not sure if anybody relies on this variable and am not feeling lucky lately with the changes. Therefore I would suggest to postpone this until we make a breaking release. Alternatively, we can add a constant alias to have our own code base aligned already

**Comment by lr4d** [comment]
> I'm not sure if anybody relies on this variable

ofc something in raq does...

**Comment by fjetter** [comment]
Thanks @lr4d

**Review by fjetter — APPROVED** [review]

**Pull request merged**
