### PR TITLE
Fix type signature of observed_values

### PR DESCRIPTION
**Pull request by xhochy**
# Description:

Briefly describe the change of behavior

- [ ] Closes #xxxx
- [ ] Changelog entry

### CODE REVIEW

**Comment by xhochy** [comment]
The failures are due to https://github.com/numpy/numpy/issues/17913

**Comment by xhochy** [comment]
We can get that unblocked when https://github.com/apache/arrow/pull/8834 is merged and also used in the numpy nightly entry.

**Comment by marco-neumann-by** [comment]
@xhochy I think this was fixed by #391. Can this PR here be closed?

**Comment by xhochy** [comment]
Yes.

**Pull request closed without merging**
