### PR TITLE
Improve predicate "syntax" error messages

### PR DESCRIPTION
**Pull request by jonashaag**

### CODE REVIEW

**Comment by fjetter** [comment]
CI job failure due to black formatting. I recommend installing the pre-commit hooks, see https://github.com/JDASoftwareGroup/kartothek/blob/master/CONTRIBUTING.md

otherwise LGTM

**Comment by jonashaag** [comment]
Fixed black.

**Comment by fjetter** [comment]
Still test is failing

**Comment by jonashaag** [comment]
Fixed tests

**Comment by jonashaag** [comment]
Anything preventing this from being merged?

**Comment by fjetter** [comment]
Thx @jonashaag !

**Pull request merged**
