### PR TITLE
Pyugrade

### PR DESCRIPTION
**Pull request by fjetter**
# Description:

Stumbled upon this in the pandas pre-commit hooks. I think this would've been incredibly useful during (or right after) the py3 migration but it still serves some value to counter deprecated behaviours and/or replaces certain expressions with more modern ones.
I like it but I don't have a strong opinion here.

see https://github.com/asottile/pyupgrade

### CODE REVIEW

**Comment by lr4d** [comment]
Very nice

**Review by lr4d — APPROVED** [review]

**Comment by lr4d** [comment]
Now we just need to find a pre-commit hook which fixes grammar errors in variables and comments

**Comment by fjetter** [comment]
I'll rerun after #431

**Comment by xhochy** [comment]
@fjetter Can you rerun/rebase? (otherwise happy to take care of that)

**Pull request closed without merging**
