### PR TITLE
remove leftovers from old metadata versions

### PR DESCRIPTION
**Pull request by crepererum**

### CODE REVIEW

**Comment by lr4d** [comment]
It would make sense to also remove the `@pytest.mark.min_metadata_version(4)` decorator which is present on a lot of tests

**Comment by crepererum** [comment]
Do we also want to remove the test fixture `metadata_version` completely or should we keep this part of the test infrastructure intact because we might need it soonish? CC @fjetter

**Comment by fjetter** [comment]
I kept both the fixture and the mark intentionally since I figured we'll require the same again at some point

I don't care too much about the decorator but I would keep the `metadata_version` as a fixture since this is a very easy way to spot breakage once we introduce a new version.

**Comment by crepererum** [comment]
codecov is a flux, I couldn't find anything that got worse.

**Pull request merged**
